services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: taskmanagerapi
#    volumes:
#      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  taskmanagerapi:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskmanagerapi